Repository bljhty/Pickup-NUS, pull requests merged in 2022-06, with the labels that each got.

#46 bottom navigation bar added
  lib/Components/Bottom_bar.dart
  lib/Components/enum.dart
  lib/Order/cart_page.dart
  lib/Order/order_directory_page.dart
  lib/Order/restaurant_directory_page.dart
Labels: enhancement

#48 Profile page added, + log out function
  lib/Components/Bottom_bar.dart
  lib/Order/cart_page.dart
  lib/Order/restaurant_directory_page.dart
  lib/Profile/profile_screen.dart
  lib/authentication/mainpage.dart
  lib/authentication/pages/orders_page.dart
Labels: priority.High

#50 Added Special Instructions textbox in food details
  lib/Order/models/food_add_on.dart
  lib/Order/models/food_detail_page.dart
  lib/Order/models/food_info.dart
  lib/Order/models/food_price_quantity.dart
Labels: enhancement

#53 removed empty folder
  lib/Buyer Side/Order pages/food details/food_detail_page.dart
  lib/Buyer Side/Order pages/food details/models/food_add_on.dart
  lib/Buyer Side/Order pages/food details/models/food_detail_image.dart
  lib/Buyer Side/Order pages/food details/models/food_info.dart
  lib/Buyer Side/Order pages/food details/models/food_price_quantity.dart
  lib/Buyer Side/Order pages/food directory/models/food_item.dart
  lib/Buyer Side/Order pages/food directory/models/food_list.dart
  lib/Buyer Side/Order pages/food directory/models/food_list_view.dart
  lib/Buyer Side/Order pages/food directory/models/restaurant_info.dart
  lib/Buyer Side/Order pages/food directory/order_directory_page.dart
  lib/Buyer Side/Order pages/restaurant selection/models/place_select.dart
  lib/Buyer Side/Order pages/restaurant selection/models/restaurant_item.dart
  lib/Buyer Side/Order pages/restaurant selection/models/restaurant_list_view.dart
  lib/Buyer Side/Order pages/restaurant selection/restaurant_directory_page.dart
  lib/Buyer Side/cart/cart_page.dart
  lib/Buyer Side/cart/models/cart_item.dart
  lib/Buyer Side/cart/models/cart_list_view.dart
  lib/Buyer Side/get_information/food.dart
  lib/Buyer Side/get_information/get_restaurant.dart
  lib/Buyer Side/get_information/place.dart
  lib/Buyer Side/get_information/restaurant.dart
  lib/Components/Bottom_bar.dart
  lib/authentication/mainpage.dart
Labels: documentation

#55 Included color scheme
  lib/Buyer Side/Order pages/food details/food_detail_page.dart
  lib/Buyer Side/Order pages/food details/models/food_detail_image.dart
  lib/Buyer Side/Order pages/food details/models/food_price_quantity.dart
  lib/Buyer Side/Order pages/food directory/models/food_item.dart
  lib/Buyer Side/Order pages/food directory/models/food_list.dart
  lib/Buyer Side/Order pages/food directory/models/food_list_view.dart
  lib/Buyer Side/Order pages/food directory/models/restaurant_info.dart
  lib/Buyer Side/Order pages/food directory/order_directory_page.dart
  lib/Buyer Side/Order pages/restaurant selection/models/place_select.dart
  lib/Buyer Side/Order pages/restaurant selection/restaurant_directory_page.dart
  lib/Buyer Side/cart/cart_page.dart
  lib/Buyer Side/cart/models/cart_list_view.dart
  lib/authentication/Merchant/merchant_register_page.dart
  lib/authentication/pages/forgot_password_page.dart
  lib/authentication/pages/login_screen.dart
  lib/authentication/pages/register_page.dart
  lib/colors.dart
Labels: documentation

#56 minor changes to fix the code
  lib/Buyer Side/Order pages/food directory/models/restaurant_info.dart
  lib/Buyer Side/Order pages/food directory/order_directory_page.dart
Labels: documentation

#57 implemented database for ordering
  lib/Buyer Side/Order pages/food details/food_detail_page.dart
  lib/Buyer Side/Order pages/food details/models/food_detail_image.dart
  lib/Buyer Side/Order pages/food details/models/food_info.dart
  lib/Buyer Side/Order pages/food details/models/food_price_quantity.dart
  lib/Buyer Side/Order pages/food directory/models/food_item.dart
  lib/Buyer Side/Order pages/food directory/models/food_list.dart
  lib/Buyer Side/Order pages/food directory/models/food_list_view.dart
  lib/Buyer Side/Order pages/food directory/models/restaurant_info.dart
  lib/Buyer Side/Order pages/food directory/order_directory_page.dart
  lib/Buyer Side/Order pages/restaurant selection/models/place_select.dart
  lib/Buyer Side/Order pages/restaurant selection/models/restaurant_item.dart
  lib/Buyer Side/Order pages/restaurant selection/models/restaurant_list_view.dart
  lib/Buyer Side/Order pages/restaurant selection/restaurant_directory_page.dart
  lib/Buyer Side/get_information/food.dart
  lib/Buyer Side/get_information/get_food.dart
  lib/Buyer Side/get_information/get_restaurant.dart
  lib/main.dart
Labels: enhancement

#59 integrated database for ordering
  lib/Buyer Side/Order pages/food details/food_detail_page.dart
  lib/Buyer Side/Order pages/food details/models/food_add_on.dart
  lib/Buyer Side/Order pages/food details/models/food_info.dart
  lib/Buyer Side/Order pages/food details/models/food_price_quantity.dart
  lib/Buyer Side/Order pages/food directory/order_directory_page.dart
  lib/Buyer Side/Order pages/restaurant selection/restaurant_directory_page.dart
  lib/Buyer Side/get_information/get_cart.dart
  lib/Buyer Side/get_information/get_food.dart
  lib/Buyer Side/get_information/get_order.dart
  lib/Buyer Side/get_information/get_username.dart
  lib/authentication/mainpage.dart
Labels: enhancement

#67 fixed issue where order information shows null
  lib/Buyer Side/Order pages/food directory/order_directory_page.dart
  lib/Buyer Side/cart/cart_page.dart
  lib/Orders/models/order_box.dart
  lib/Orders/orders_page.dart
  lib/Profile/Past Orders/past_order_page.dart
Labels: bug

#68 Modified code to allow it to run
  lib/Buyer Side/cart/cart_page.dart
  lib/Profile/profile_screen.dart
  lib/main.dart
Labels: bug

#69 fixed minor bugs
  lib/Buyer Side/Order pages/food directory/order_directory_page.dart
  lib/Buyer Side/Order pages/restaurant selection/restaurant_directory_page.dart
  lib/Buyer Side/cart/cart_page.dart
  lib/Orders/orders_page.dart
  lib/Profile/profile_screen.dart
Labels: bug

#72 merchant can change restaurant status
  lib/Buyer Side/get_information/get_restaurant.dart
  lib/Merchant side/open_for_order.dart
  lib/authentication/home.dart
Labels: enhancement

#74 arranged files and directories
  lib/Buyer Side/Components/Bottom_bar.dart
  lib/Buyer Side/Components/enum.dart
  lib/Buyer Side/Order pages/food directory/models/food_list.dart
  lib/Buyer Side/Order pages/food directory/models/food_list_view.dart
  lib/Buyer Side/Order pages/food directory/order_directory_page.dart
  lib/Buyer Side/Order pages/restaurant selection/models/restaurant_list_view.dart
  lib/Buyer Side/Order pages/restaurant selection/restaurant_directory_page.dart
  lib/Buyer Side/Orders/models/order_box.dart
  lib/Buyer Side/Orders/models/order_ready_box.dart
  lib/Buyer Side/Orders/models/orders_preparing_list_view.dart
  lib/Buyer Side/Orders/models/orders_ready_list_view.dart
  lib/Buyer Side/Orders/orders_page.dart
  lib/Buyer Side/Profile/Past Orders/models/past_order_item.dart
  lib/Buyer Side/Profile/Past Orders/models/past_order_list_view.dart
  lib/Buyer Side/Profile/Past Orders/past_order_page.dart
  lib/Buyer Side/Profile/card_info.dart
  lib/Buyer Side/Profile/profile_screen.dart
  lib/Buyer Side/cart/cart_page.dart
  lib/Buyer Side/cart/models/cart_item.dart
  lib/Buyer Side/cart/models/cart_list_view.dart
  lib/Merchant side/Merchant Home Page/models/orders_list_view.dart
  lib/Merchant side/Profile/Past Orders/merchant_past_orders_page.dart
  lib/Merchant side/Profile/merchant_profile_page.dart
  lib/authentication/Merchant/merchant_register_page.dart
  lib/authentication/pages/register_page.dart
Labels: documentation

#76 added a collected and ready button for orders
  lib/Buyer Side/Orders/models/orders_ready_list_view.dart
  lib/Merchant side/Merchant Home Page/merchant_home_page.dart
  lib/Merchant side/Merchant Home Page/models/orders_list_view.dart
  lib/Merchant side/Profile/Past Orders/merchant_past_orders_page.dart
Labels: enhancement

#78 made minor adjustments
  assets/images/chicken_cutlet.png
  assets/images/crispy_chicken.png
  assets/images/techno_western.png
  lib/Buyer Side/Orders/orders_page.dart
  lib/authentication/pages/forgot_password_page.dart
  lib/authentication/pages/register_page.dart
  pubspec.yaml
Labels: documentation

#79 started on edit menu page
  android/app/src/main/AndroidManifest.xml
  assets/icons/logo_foreground.png
  ios/Runner/Info.plist
  lib/Buyer Side/Profile/edit menu/edit_menu_page.dart
  lib/Buyer Side/Profile/edit menu/models/edit_item_page.dart
  lib/Buyer Side/Profile/edit menu/models/item_box.dart
  lib/Buyer Side/Profile/edit menu/models/item_list_view.dart
  lib/Buyer Side/Profile/edit menu/models/menu_type_list.dart
  lib/Buyer Side/get_information/food.dart
  lib/Buyer Side/get_information/place.dart
  lib/Buyer Side/get_information/restaurant.dart
  lib/Merchant side/Profile/merchant_profile_page.dart
  pubspec.yaml
Labels: enhancement
